package com.springboot.example.dao;

import com.springboot.example.models.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
    /**
     * 根据用户验证
     */
    int checkByUsername(String username);
    /**
     * 根据邮箱验证
     */
    int checkByEmail(String email);
    /**
     * 用户登录，根据用户名和密码登录
     */
    User selectByUsernameAndPassword(@Param("username") String username, @Param("password") String password);

    /**
     * 根据用户名找回密码问题
     * @param username
     * @return
     */
    User forgetGetQuestion(String username);

    /**
     * 检查问题答案
     * @param username
     * @param question
     * @param anwser
     * @return
     */
    int forgetCheckAnswer(@Param("username") String username, @Param("question") String question,@Param("answer") String answer);

    int updatePasswordByUsername(@Param("username") String username,@Param("password") String password);
}